name: Tagged

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual trigger'
        required: true
        default: 'Get tag'


jobs:

  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Optionally: unshallow as a separate operation
    # - name: Unshallow
    #   run: git fetch --prune --unshallow
    - name: Find Tag
      id: tagger
      uses: digital-ai/query-tag-action@v2-rc1
      with:
        include: '*nightly*'
        commit-ish: 'HEAD'
        exact-match: 'true' 
        # if you unshallow in a separate step, use the following option:
        # skip-unshallow: 'true'
    - name: Show Tag
      if: contains(steps.tagger.outputs.tag, 'nightly')
      id: display
      run: |
        echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'

    - name: No Tag
      if: contains(steps.tagger.outputs.tag, 'NO_TAGS')
      id: message
      run: |
        echo 'HEAD is not tagged'

    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        # Command to execute on the remote server.
        command: /data/lisbon/nightly.sh
        host: ${{ secrets.EC2_HOSTNAME }}
        username: ${{ secrets.EC2_USER }}
        privateKey: ${{ secrets.EC2_KEY }}
